 Python Version Check

In [ ]:
import sys
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
  print("Hello, World!")
  print(f"Python version: {sys.version}")
else:
  print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]


 Difference between Mutable and Immutable Data Types.

In [ ]:
my_list = [1, 2, 3]
print("Original List:", my_list)
my_list.append(4)
print("Modified List:", my_list)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


4.1 Exercise on Functions:
 Task- 1:
 Create a Python program that converts between different units of measurement.

In [ ]:
def convert_units(value, choice):
  """Convert between units baded on user choice.
  Parameters:
  value (float): Value to convert
  choice (int): Conversion option (1-6)

  Returns:
  floatL Converted value
  """
  conversions = {
      1: (value * 3.28084, "meters", "feet"),
      2: (value * 0.3048, "feet", "meters"),
      3: (value * 2.20462, "kg", "lbs"),
      4: (value * 0.453592, "lbs", "kg"),
      5: (value * 0.264172, "liters", "gallons"),
      6: (value * 3.78541, "gallons", "liters")
  }

  result, from_unit, to_unit = conversions[choice]
  return round(result, 2), from_unit, to_unit

def main():
  print("Choose conversion:")
  print("1. Meters to Feet")
  print("2. Feet to Meters")
  print("3. Kilograms to Pounds")
  print("4. Pounds to Kilograms")
  print("5. Liters to Gallons")
  print("6. Gallons to Liters")

  try:
    choice = int(input("Enter choice (1-6):"))
    if choice not in range (1,7):
      print("Please enter a number between 1 and 6")
      return

    value = float(input("Enter value:"))
    if value<0:
      print("Value cannot be negative")
      return

    result, from_unit, to_unit = convert_units(value, choice)
    print(f"{value} {from_unit} = {result} {to_unit}")

  except ValueError:
    print("Invalid input: Please enter numbers only")

main()

Choose conversion:
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter choice (1-6):5
Enter value:99
99.0 liters = 26.15 gallons


 Task- 2:
 Create a Python program that performs various mathematical operations on a list of numbers.

In [ ]:
def calculate_sum(numbers):
  """Calculate the sum of a list of numbers.

  Parameters: numbers (list): List of numbers

  Returns: float: Sum of all number """
  return sum(numbers)

def calculate_average(numbers):
  """Calculate the average of a list of numbers.

  Parameters: numbers (list): List of numbers

  Returns: float: Average of all numbers """
  return sum(numbers)/len(numbers)

def find_maximum(numbers):
  """Find the maximum value in a list of numbers.

  Parameters: numbers (list): List of numbers

  Returns: float: Maximum value """

  return max(numbers)

def find_minimum(numbers):
  """Find the minimum value in a list of numbers.

  Parameters: numbers (list): List of numbers

  Returns: float: Minimum value """
  return min(numbers)

def main():
  print("Mathematical Operations:")
  print("1. Sum")
  print("2. Average")
  print("3. Maximum")
  print("4. Minimum")

  try:
    choice = int(input("Enter operation choice (1-4):"))
    if choice not in range (1,5):
      print("Please enter a number between 1 and 4")
      return

    numbers_input = input("Enter numbers separated by spaces:")
    numbers = [float(num) for num in numbers_input.split()]

    if not numbers:
      print("Error: Empty list provided")
      return

    operations = {
        1: (calculate_sum, "Sum"),
        2: (calculate_average, "Average"),
        3: (find_maximum, "Maximum"),
        4: (find_minimum, "Minimum")
    }

    operation_func, operation_name = operations[choice]
    result = operation_func(numbers)
    print(f"{operation_name} of {numbers} = {round(result, 2)}")

  except ValueError:
    print("Invalid input: Please enter valid numbers only")
  except ZeroDivisionError:
    print("Error: Cannot calculate average of empty list")

main()

Mathematical Operations:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter operation choice (1-4):4
Enter numbers separated by spaces:1 5 77 88 98
Minimum of [1.0, 5.0, 77.0, 88.0, 98.0] = 1.0


 4.2 Exercise on List Manipulation:


In [ ]:
def extract_every_other(lst):
  return lst[::2]

def get_sublist(lst, start, end):
  return lst[start:end + 1]

def reverse_slicing(lst):
  return lst[::-1]

def remove_first_last(lst):
  return lst[1:-1]

def get_first_n(lst, n):
  return lst[:n]

def get_last_n(lst,n):
  return lst[-n:]

def reverse_skip(lst):
  return lst[-2::-2]

def main():
  lst = [1,2,3,4,5,6]
  print(f"Original list: {lst}")
  print("Every other element:", extract_every_other(lst))
  print("Sublist (2,4):", get_sublist(lst, 2,4))
  print("Reversed list:", reverse_slicing(lst))
  print("Without first and last:", remove_first_last(lst))
  print("First 3 elements:", get_first_n(lst,3))
  print("Last 2 elements:", get_last_n(lst,2))
  print("Reverse skip:", reverse_skip(lst))


main()

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]
Sublist (2,4): [3, 4, 5]
Reversed list: [6, 5, 4, 3, 2, 1]
Without first and last: [2, 3, 4, 5]
First 3 elements: [1, 2, 3]
Last 2 elements: [5, 6]
Reverse skip: [5, 3, 1]


4.3 Exercise on Nested List:

In [ ]:
def flatten(lst):
  flattened = []
  for item in lst:
    if isinstance(item, list):
      flattened.extend(flatten(item))
    else:
      flattened.append(item)
  return flattened

def access_nested_element(lst, indices):
  result = lst
  for index in indices:
    result = result[index]
  return result

def sum_nested(lst):
  total = 0
  for item in lst:
    if isinstance(item, list):
      total += sum_nested(item)
    elif isinstance(item, (int,float)):
      total += item
  return total

def remove_element(lst,elem):
  result = []
  for item in lst:
    if isinstance(item,list):
      result.append(remove_element(item, elem))
    elif item != elem:
      result.append(item)
  return result

def find_max(lst):
  flattened = flatten(lst)
  return max(flattened) if flattened else None

def count_occurences(lst, elem):
  count = 0
  for item in lst:
    if isinstance(item, list):
      count ++ count_occurences(item, elem)
    elif item == elem:
      count += 1
  return count

def deep_flatten(lst):
  flattened =[]
  for item in lst:
    if isinstance(item, list):
      flattened.extend(deep_flatten(item))
    else:
      flattened.append(item)
  return flattened

def average_nested(lst):
  flat_list = flatten(lst)
  return sum(flat_list) / len(flat_list) if flat_list else 0

def main():
  nested_list1 = [[1,2], [3,4], [5]]
  nested_list2 = [[1,2,3], [4,5,6], [7,8,9]]
  nested_list3 =[[1,2], [3,[4,5]],6]
  nested_list4 =[[1,2],[2,3],[2,4]]
  nested_list5 = [[[1,2], [3,4]],[[5,6], [7,8]]]

  print("1.Flatten:", flatten(nested_list1))
  print("2. Access element [1,2]:", access_nested_element(nested_list2, [1,2]))
  print("3. Sum:", sum_nested(nested_list3))
  print("4. Remove 2:", remove_element(nested_list4, 2))
  print("5. Max:", find_max(nested_list3))
  print("6. Count 2:", count_occurences(nested_list4, 2))
  print("7. Deep flatten:", deep_flatten(nested_list5))
  print("8. Average:", average_nested(nested_list1))

main()

1.Flatten: [1, 2, 3, 4, 5]
2. Access element [1,2]: 6
3. Sum: 21
4. Remove 2: [[1], [3], [4]]
5. Max: 6
6. Count 2: 0
7. Deep flatten: [1, 2, 3, 4, 5, 6, 7, 8]
8. Average: 3.0


10 To- Do- NumPy
 Please complete all the problems listed below:
 10.1 Basic Vector and Matrix Operation with Numpy.
 Problem- 1: Array Creation:
 Complete the following Tasks:
 1. Initialize an empty array with size 2X2.
 2. Initialize an all one array with size 4X2.
 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

def array_creation():
  empty_array = np.empty((2,2))
  print("1. Empty 2x2 array:")
  print(empty_array)
  print()

  ones_array = np.ones((4,2))
  print("2. All ones 4x2 array:")
  print(ones_array)
  print()

  filled_array = np.full((3,3), fill_value=7)
  print("3. 3x3 array filled with 7:")
  print(filled_array)
  print()

  sample_array = np.array([[1,2], [3,4]])
  zeros_like_array = np.zeros_like(sample_array)
  print("4. Zeros array with same shape as [[1,2], [3,4]]:")
  print(zeros_like_array)
  print()

  ones_like_array = np.ones_like(sample_array)
  print("5. Ones array with same shape as [[1,2], [3,4]]:")
  print(ones_like_array)
  print()

  new_list = [1,2,3,4]
  numpy_array = np.array(new_list)
  print("6. Numpy array from list [1,2,3,4]:")
  print(numpy_array)
  print("Type:", type(numpy_array))

array_creation()


1. Empty 2x2 array:
[[0.73170129 0.76261359]
 [0.07019702 0.96364827]]

2. All ones 4x2 array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. 3x3 array filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros array with same shape as [[1,2], [3,4]]:
[[0 0]
 [0 0]]

5. Ones array with same shape as [[1,2], [3,4]]:
[[1 1]
 [1 1]]

6. Numpy array from list [1,2,3,4]:
[1 2 3 4]
Type: <class 'numpy.ndarray'>


 Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:
 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
 2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}
 3. Create a 3X3 identity matrix.{Hint:np.eye()}
 4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}
 5. Create a 10X10 array with random values and find the minimum and maximum values.
 6. Create a zero array of size 10 and replace 5th element with 1.
 7. Reverse an array arr = [1,2,0,0,4,0].
 8. Create a 2d array with 1 on border and 0 inside.
 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

def array_manipulation():
  range_array = np.arange(10,50)
  print("1. Array from 10 to 49:")
  print(range_array)
  print()

  matrix_3x3 = np.arange(9).reshape(3,3)
  print("2. 3x3 matrix (0-8):")
  print(matrix_3x3)
  print()

  identity_matrix = np.eye(3)
  print("3. 3x3 identity matrix:")
  print(identity_matrix)
  print()

  random_array = np.random.random(30)
  mean_value = random_array.mean()
  print("4. Random array (first 5 elements) and mean:")
  print(random_array[:5])
  print("Mean:", mean_value)
  print()

  random_10x10 = np.random.random((10, 10))
  min_value = random_10x10.min()
  max_value = random_10x10.max()
  print("5. 10x10 random array (first 2x2 corner):")
  print(random_10x10[:2, :2])
  print("Minimum:", min_value)
  print("Maximum:", max_value)
  print()

  zero_array = np.zeros(10)
  zero_array[4] = 1
  print("6. Zero array with 5th element as 1:")
  print(zero_array)
  print()

  arr = np.array([1,2,0,0,4,0])
  reversed_arr = arr[::-1]
  print("7. Reversed array [1,2,0,0,4,0]:")
  print(reversed_arr)
  print()

  border_array = np.ones((5,5))
  border_array[1:-1, 1:-1] = 0
  print("8. 5x5 array with 1 on border, 0 inside:")
  print(border_array)
  print()

  checkerboard = np.zeros((8,8))
  checkerboard[1::2, ::2] = 1
  checkerboard[::2, 1::2] = 1
  print("9. 8x8 checkerboard pattern:")
  print(checkerboard)

array_manipulation()

1. Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0-8):
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (first 5 elements) and mean:
[0.72980663 0.32069849 0.12476316 0.17470817 0.9061561 ]
Mean: 0.4970454816551336

5. 10x10 random array (first 2x2 corner):
[[0.73170129 0.76261359]
 [0.07019702 0.96364827]]
Minimum: 0.0031296136755967208
Maximum: 0.9854404772888933

6. Zero array with 5th element as 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array [1,2,0,0,4,0]:
[0 4 0 0 2 1]

8. 5x5 array with 1 on border, 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 checkerboard pattern:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 

Problem- 3: Array Operations:
 For the following arrays:
 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
 v = np.array([9,10]) and w = np.array([11,12]);
 Complete all the task using numpy:
 1. Add the two array.
 2. Subtract the two array.
 3. Multiply the array with any integers of your choice.
 4. Find the square of each element of the array.
 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.
 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

def array_operation():
  x = np.array([[1,2], [3,5]])
  y = np.array([[5,6], [7,8]])
  v = np.array([9,10])
  w = np.array([11,12])

  addition_add = x+y
  print("1. Addition of x an y:")
  print(addition_add)
  print()

  subtract_sub = x-y
  print("2. Subtraction of x an y:")
  print(subtract_sub)
  print()

  multiplication_multiply = x*3
  print("3. Multiply of with 3:")
  print(multiplication_multiply)
  print()

  square_square = np.square(x)
  print("4. Square of each element in x:")
  print(square_square)
  print()

  v_w_dot = np.dot(v,w)
  x_v_dot = np.dot(x,v)
  x_y_dot = np.dot(x,y)
  print("5. Dot products:")
  print("v and w:", v_w_dot)
  print("x and v:", x_v_dot)
  print("x and y:")
  print(x_y_dot)
  print()

  concat_rows = np.concatenate((x,y), axis=0)
  concat_cols = np.vstack((v,w))
  print("6. Concatenations:")
  print("x and y along rows:")
  print(concat_rows)
  print("v and w along columns:")
  print(concat_cols)
  print()

  try:
    concat_x_v = np.concatenate((x,v))
    print("7. Concatenation of x and v:")
    print(concat_x_v)
  except ValueError as e:
    print("7. Concatenation of x and v failed:")
    print("Error:", str(e))
    print("Explanation: The error occured because x is a 2D array (2x2) an v is a 1D array (2 elements).")

array_operation()


1. Addition of x an y:
[[ 6  8]
 [10 13]]

2. Subtraction of x an y:
[[-4 -4]
 [-4 -3]]

3. Multiply of with 3:
[[ 3  6]
 [ 9 15]]

4. Square of each element in x:
[[ 1  4]
 [ 9 25]]

5. Dot products:
v and w: 219
x and v: [29 77]
x and y:
[[19 22]
 [50 58]]

6. Concatenations:
x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along columns:
[[ 9 10]
 [11 12]]

7. Concatenation of x and v failed:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: The error occured because x is a 2D array (2x2) an v is a 1D array (2 elements).


In [ ]:
import numpy as np

def matrix_operations():
  A = np.array([[3,4], [7,8]])
  B = np.array([[5,3], [2,1]])

  A_inv = np.linalg.inv(A)
  identity_proof = np.dot (A, A_inv)
  print("1. Proving A * A^-1 = I:")
  print("A * A^-1 = I:")
  print(identity_proof.round())
  print("Verification: Close to identify matrix (1s on diagonal, 0s lesewhere)")

  AB = np.dot(A, B)
  BA = np.dot(B, A)
  print("2. Testing AB = BA:")
  print("AB:")
  print(AB)
  print("BA:")
  print(BA)
  print("Verification: AB ≠ BA (matrices are not equal) ")
  print()

  AB_transpose = np.transpose(AB)
  B_transpose = np.transpose(B)
  A_transpose = np.transpose(A)
  BT_AT = np.dot(B_transpose, A_transpose)
  print("3. Proving (AB)^T = B^T * A^T:")
  print("(AB)^T:")
  print(AB_transpose)
  print("B^T * A^T:")
  print(BT_AT)
  print("Verification: (AB)^T = B^T * A^T (matrices are equal)")
  print()

  coeff_matrix = np.array([[2, -3, 1],
                          [1, -1, 2],
                          [3, 1, -1]])
  constants = np.array([-1, -3, 9])

  coeff_inv = np.linalg.inv(coeff_matrix)
  solution = np.dot(coeff_inv, constants)
  print("4. Solving system of equations using inverse method:")
  print("Coefficient matrix A:")
  print(coeff_matrix)
  print("Constants B:", constants)
  print("Solution X (x, y, z):", solution)
  print("Verification: A * X should equal B")
  print(np.dot(coeff_matrix, solution).round())
  print()

  solution_linalg = np.linalg.solve(coeff_matrix, constants)
  print("5. Solving using np.linalg.solve:")
  print("Solution X (x, y, z):", solution_linalg)
  print("Verification: Should match inverse method solution")

matrix_operations()

1. Proving A * A^-1 = I:
A * A^-1 = I:
[[1. 0.]
 [0. 1.]]
Verification: Close to identify matrix (1s on diagonal, 0s lesewhere)
2. Testing AB = BA:
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Verification: AB ≠ BA (matrices are not equal) 

3. Proving (AB)^T = B^T * A^T:
(AB)^T:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]
Verification: (AB)^T = B^T * A^T (matrices are equal)

4. Solving system of equations using inverse method:
Coefficient matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constants B: [-1 -3  9]
Solution X (x, y, z): [ 2.  1. -2.]
Verification: A * X should equal B
[-1. -3.  9.]

5. Solving using np.linalg.solve:
Solution X (x, y, z): [ 2.  1. -2.]
Verification: Should match inverse method solution


 10.2 Experiment: How Fast is Numpy?
 In this exercise, you will compare the performance and implementation of operations using plain Python
 lists (arrays) and NumPy arrays. Follow the instructions:
 1. Element-wise Addition:
 • Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure
 and Print the time taken for this operation.
 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.
 2. Element-wise Multiplication
 • Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000.
 Measure and Print the time taken for this operation.
 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.
 3. Dot Product
 • Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and
 Print the time taken for this operation.
 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.
 4. Matrix Multiplication
 • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea
sure and print the time taken for this operation.
 • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
 Measure and print the time taken for this operation

In [ ]:
import numpy as np
import time
import random

def performance_comparison():
    LIST_SIZE = 1_000_000
    MATRIX_SIZE = 1000

    print("1. Element-wise Addition:")
    list1 = [random.random() for _ in range(LIST_SIZE)]
    list2 = [random.random() for _ in range(LIST_SIZE)]
    start_time = time.time()
    list_addition = [x + y for x, y in zip(list1, list2)]
    list_add_time = time.time() - start_time
    print(f"Python Lists: {list_add_time:.4f} seconds")

    arr1 = np.random.random(LIST_SIZE)
    arr2 = np.random.random(LIST_SIZE)
    start_time = time.time()
    numpy_addition = arr1 + arr2
    numpy_add_time = time.time() - start_time
    print(f"NumPy Arrays: {numpy_add_time:.4f} seconds")
    print()

    print("2. Element-wise Multiplication:")
    start_time = time.time()
    list_multiplication = [x * y for x, y in zip(list1, list2)]
    list_mult_time = time.time() - start_time
    print(f"Python Lists: {list_mult_time:.4f} seconds")

    start_time = time.time()
    numpy_multiplication = arr1 * arr2
    numpy_mult_time = time.time() - start_time
    print(f"NumPy Arrays: {numpy_mult_time:.4f} seconds")
    print()

    print("3. Dot Product:")
    start_time = time.time()
    list_dot = sum(x * y for x, y in zip(list1, list2))
    list_dot_time = time.time() - start_time
    print(f"Python Lists: {list_dot_time:.4f} seconds")

    start_time = time.time()
    numpy_dot = np.dot(arr1, arr2)
    numpy_dot_time = time.time() - start_time
    print(f"NumPy Arrays: {numpy_dot_time:.4f} seconds")
    print()

    print("4. Matrix Multiplication (1000x1000):")
    matrix1 = [[random.random() for _ in range(MATRIX_SIZE)] for _ in range(MATRIX_SIZE)]
    matrix2 = [[random.random() for _ in range(MATRIX_SIZE)] for _ in range(MATRIX_SIZE)]
    result = [[0] * MATRIX_SIZE for _ in range(MATRIX_SIZE)]

    start_time = time.time()
    for i in range(MATRIX_SIZE):
        for j in range(MATRIX_SIZE):
            for k in range(MATRIX_SIZE):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    list_matrix_time = time.time() - start_time
    print(f"Python Lists: {list_matrix_time:.4f} seconds")

    numpy_matrix1 = np.random.random((MATRIX_SIZE, MATRIX_SIZE))
    numpy_matrix2 = np.random.random((MATRIX_SIZE, MATRIX_SIZE))
    start_time = time.time()
    numpy_matrix_result = np.dot(numpy_matrix1, numpy_matrix2)
    numpy_matrix_time = time.time() - start_time
    print(f"NumPy Arrays: {numpy_matrix_time:.4f} seconds")

performance_comparison()

1. Element-wise Addition:
Python Lists: 0.0691 seconds
NumPy Arrays: 0.0042 seconds

2. Element-wise Multiplication:
Python Lists: 0.0673 seconds
NumPy Arrays: 0.0045 seconds

3. Dot Product:
Python Lists: 0.0671 seconds
NumPy Arrays: 0.0013 seconds

4. Matrix Multiplication (1000x1000):
Python Lists: 201.9277 seconds
NumPy Arrays: 0.1258 seconds
